# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/school/Maths/数字电路/watch_king/watch.cache/wt [current_project]
set_property parent.project_path E:/school/Maths/数字电路/watch_king/watch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/school/Maths/数字电路/watch_king/watch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/school/Maths/数字电路/watch_king/watch.srcs/sources_1/imports/6_watch/watch.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/school/Maths/数字电路/watch_king/watch.srcs/constrs_1/imports/6_watch/watch.xdc
set_property used_in_implementation false [get_files E:/school/Maths/数字电路/watch_king/watch.srcs/constrs_1/imports/6_watch/watch.xdc]


synth_design -top watch -part xc7a200tfbg676-2


write_checkpoint -force -noxdef watch.dcp

catch { report_utilization -file watch_utilization_synth.rpt -pb watch_utilization_synth.pb }
